### ISSUE TITLE
Running Sora in Codespace shows "Upgrade Required"

### ISSUE THREAD

**Issue by iamkgehlot** [Khanhtran47/Sora#277]
Running Sora as it is shows "Upgrade Required" on server.

**Comment by ctuanle** [comment]
@iamkgehlot Hi, did you open the preview link on port 8002 ?
For me, there are two forwarded ports and  it works normally on 3000.

![image](https://user-images.githubusercontent.com/70543626/205449293-a5cb25a9-8a16-4e1e-82d0-cf7ef16df9de.png)

![image](https://user-images.githubusercontent.com/70543626/205449332-d068e32a-f642-4938-979c-bf59799f1721.png)

**Comment by iamkgehlot** [comment]
@ctuanle is any thing needed to be configured prior running sora ? is there any guide for initial setup?

**Comment by ctuanle** [comment]
@iamkgehlot for now we don't have any guide yet, but shortly all you need to do is create your own version of .env based on .env-example, then fill it with your secrets
