### ISSUE TITLE
Loklok API URL

### ISSUE THREAD

**Issue by JamesHawkinss** [Khanhtran47/Sora#289]
Hi there, I was wondering if you're able to share the LokLok API URL that you're using in this project? 

I had found https://ga-mobile-api.loklok.tv/cms/app online, but it doesn't match the calls you're making and provides inconsistent results. Any help you can provide would be appreciated :)

**Comment by Khanhtran47** [comment]
@JamesHawkinss Hi, you can use loklok api from this [doc](https://documenter.getpostman.com/view/18986031/UVXdNeFD). In this project, I created a custom api from that using Vercel's serverless functions or edge functions (remember to change the region to "Sydney, Australia").
