### ISSUE TITLE
Please help me create a user account

### ISSUE THREAD

**Issue by lamhoang1256** [Khanhtran47/Sora#293]
Hey Bro, I really like your movie project. 
Can you create a user account for me to experience the website? 
And it seems the Loklok movie source can't be used. Example https://akm-cdn-play.loklok.tv/f9f4630bc9284c3b833b76468ba277f7/1c4b5007241f47e9a40edb542ac37f56-091771faf7962442ca8548fb18eda9bc-hd.m3u8?hdnts=exp=1671630672-acl=/*-hmac=43aeeacfdcaf02ff370dea7feecfee0303fdaffe97dcd7c882377e9e2c8803b5

**Comment by Khanhtran47** [comment]
@lamhoang1256 I sent to your email (lamhoang1256@gmail.com) an invitation to use, you can accept it and use the website

> And it seems the Loklok movie source can't be used. Example https://akm-cdn-play.loklok.tv/f9f4630bc9284c3b833b76468ba277f7/1c4b5007241f47e9a40edb542ac37f56-091771faf7962442ca8548fb18eda9bc-hd.m3u8?hdnts=exp=1671630672-acl=/*-hmac=43aeeacfdcaf02ff370dea7feecfee0303fdaffe97dcd7c882377e9e2c8803b5

I think you have to add a proxy and add a referer to loklok website for playing this.

**Comment by shiyiya** [comment]
+1 🤪
@Khanhtran47

**Comment by Khanhtran47** [comment]
@shiyiya you can try to [sign up](https://sora-anime.vercel.app/sign-up) again

**Comment by shiyiya** [comment]
@Khanhtran47 
![image](https://user-images.githubusercontent.com/34017352/211141389-4a16e95d-1cff-445e-97b0-a38c53f0e747.png)

**Comment by shiyiya** [comment]
@Khanhtran47 
xx.xx@xx.com error
xxx@xx.com  ok
