### ISSUE TITLE
Account and Player Settings

### ISSUE THREAD

**Issue by HassanHaji22** [Khanhtran47/Sora#302]
Hi, thank you so much for this amazing project.
I have downloaded the app by copying the link into another window and hitting "install to homescreen" and i have signed up and confirmed my email.
For some reason i can't get into the account and player options in the settings menu, and it just really bugs me that the subtitles are always on by default, do i have to wait sometime after confirming my email to have access to those menus? or is there another step i missed? 

Thanks in advance ❤️

**Comment by Khanhtran47** [comment]
@HassanHaji22 Hi, thanks for interested in this project. The player option in the setting menu is just a placeholder right now, I will develop that section in the future. I want to finish some designs and features in the player before developing player setting.
