### ISSUE TITLE
anime OP/ED skip

### ISSUE THREAD

**Issue by himanshu8443** [Khanhtran47/Sora#304]
can Zoro opening skip be added in the player or Aniskip support
And the site works fine in Edge but lags while scrolling in Brave browser and some other Chromium-based browsers

**Comment by Khanhtran47** [comment]
> can Zoro opening skip be added in the player or Aniskip support 

@himanshu8443 yeah, I think I can add Aniskip support after finishing some features in player
> And the site works fine in Edge but lags while scrolling in Brave browser and some other Chromium-based browsers
Maybe performance issue of Nextui for some Chromium-based browsers, I use Chrome, and it's work fine to me
