### ISSUE TITLE
Loklok API

### ISSUE THREAD

**Issue by gabinfinity** [Khanhtran47/Sora#311]
I did everything right but its not working

![image](https://user-images.githubusercontent.com/59806981/214919509-ae84b325-ac81-48d0-9faf-33d174927c91.png)
![image](https://user-images.githubusercontent.com/59806981/214919543-6a344edd-16a8-48e5-bc87-67bc5b8962cc.png)

**Comment by Khanhtran47** [comment]
@gabinfinity I created a custom api from loklok api using serverless function, but I can't make it public. Someone else used it 2 months ago and vercel block my account twice because it reached its limit usage.

**Comment by gabinfinity** [comment]
I have an api, can you help me? I can send to you

**Comment by gabinfinity** [comment]
do you have any contact?

**Comment by gabinfinity** [comment]
![image](https://user-images.githubusercontent.com/59806981/214982633-22bf853a-f4fa-4dd2-af39-5ef80e083be4.png)
I just send to your email

**Comment by Khanhtran47** [comment]
@gabinfinity I don't want to do provider's part now 😵‍💫, but I'll add your api later

**Comment by gabinfinity** [comment]
Thanks bro. Please dont release for everyone the api url

**Comment by gabinfinity** [comment]
Hey bro, did the api adaptation work?

**Comment by smolgrrr** [comment]
bump

**Comment by Khanhtran47** [comment]
> Hey bro, did the api adaptation work?

@gabinfinity I haven't done it yet, but I think it works

**Comment by gabinfinity** [comment]
You must to use sydney location on vercel

**Comment by gabinfinity** [comment]
Ikay bro im excited for it

**Comment by gabinfinity** [comment]
any update?
