### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by gabinfinity** [Khanhtran47/Sora#316]
When you click the Watch Now button on a TV SHOWS, it returns an error. In movies this does not happen. I suggest removing the Watch Now button for TV SHOWS. Or make it scroll down to the seasons.
![image](https://user-images.githubusercontent.com/59806981/215221299-2f1f9fcd-6b91-4ab5-810f-bbb15c3f075b.png)

**Comment by Khanhtran47** [comment]
@gabinfinity Can you show me the error ?
Normally, the select provider modal is opened after clicking the Watch Now button and navigating to season 1, episode 1 after choosing the provider.

![image](https://user-images.githubusercontent.com/54718468/215255523-74391d38-9bce-43f2-a11d-71c466d6f8a4.png)

**Comment by gabinfinity** [comment]
WTF It was giving error. Redirected to a 404 page. But its working now

**Comment by Khanhtran47** [comment]
Ah, that's another error. It happens when you go to the web and do nothing for a while, and you come back, press or go to another page and you get a 404 error. I will try to fix it.

**Comment by gabinfinity** [comment]
Ah, I noticed that, I just forgot
