### ISSUE TITLE
`Player` bgColor 🥲

### ISSUE THREAD

**Issue by shenlong616** [Khanhtran47/Sora#330]
Chào bạn!

Bạn có thể thêm tùy chọn tắt `màu nền` của trình phát đc ko!

- `Trước khi` (như này trông hoe mắt qá)
![image](https://user-images.githubusercontent.com/15698245/220133761-d016b4a4-74f1-4ca0-b365-480fe75367d0.png)
![image](https://user-images.githubusercontent.com/15698245/220135998-1d7457c3-b4d2-4288-ab4b-dd458023ac5e.png)
![image](https://user-images.githubusercontent.com/15698245/220136200-94b5a6e7-c836-4358-aafa-b7f010834ab3.png)

- `Sau khi` (phần này mình tải phim về)
![image](https://user-images.githubusercontent.com/15698245/220133595-d0e9adc7-e9b5-4f30-832a-029d5c57e04c.png)

**Comment by Khanhtran47** [comment]
@shenlong616 mình đổi background của video thành đen rồi 😅

**Comment by shenlong616** [comment]
@Khanhtran47 cảm ơn b
