### ISSUE TITLE
Xin source code của proxy api

### ISSUE THREAD

**Issue by lamhoang1256** [Khanhtran47/Sora#337]
Em chào bác ạ. Em có làm 1 project xem phim với **Loklok** thì bị lỗi cors. E có tìm thử vài proxy để sử dụng nhưng vẫn bị lỗi cors. Và e thấy proxy **https://sora-proxy.vercel.app** của bác hoạt động quá tốt. Nên e muốn hỏi không biết bác có thể cho e xin source code của proxy để tham khảo build 1 proxy để dùng được không ạ. Em cám ơn ☺️

**Comment by hexated** [comment]
> Em chào bác ạ. Em có làm 1 project xem phim với **Loklok** thì bị lỗi cors. E có tìm thử vài proxy để sử dụng nhưng vẫn bị lỗi cors. Và e thấy proxy **https://sora-proxy.vercel.app** của bác hoạt động quá tốt. Nên e muốn hỏi không biết bác có thể cho e xin source code của proxy để tham khảo build 1 proxy để dùng được không ạ. Em cám ơn ☺️

You can try consumet cors, it much better
https://github.com/consumet/cors-anywhere

**Comment by lamhoang1256** [comment]
@hexated Oh thank you very much. I really enjoyed your Cloudstream with SoraStream too. It's really amazing and I really admire you😍

**Comment by Khanhtran47** [comment]
@lamhoang1256 bạn có thể xem repo này https://github.com/hoangvu12/requests-proxy, mình cũng tham khảo từ đó và viết lại bằng remix.

**Comment by lamhoang1256** [comment]
@Khanhtran47 Ngại quá bác em có dùng thử https://github.com/hoangvu12/requests-proxy bác gợi ý e rồi nhưng vẫn lỗi **403**, có lẽ do set chưa đúng refer (do api của app nên e ko biết chính xác url) hoặc thiếu params nào đó, bác có thể gợi ý giúp e không. Em cảm ơn nhiều

`http://localhost:3012/proxy?url=https://akm-cdn-play.loklok.tv/9e8aaacfe5d249bc926ff560dc4e4027/d687353b6e684791b80d19229376da0b-a402848c2deeea056c8f833b4556f739-hd.m3u8?hdnts=exp=1678036722-acl=/*-hmac=344df3c4303ce9530eb1d6d9fe72725a0d741a218135f099e589c41605689e28&appendReqHeaders=[["referer": "https://loklok.com"], ["origin": "https://loklok.com"]]`

**Comment by Khanhtran47** [comment]
@lamhoang1256 cdn của mobile thì bạn bỏ hết referer với origin đi là đc, còn cdn của web thì mới cần thêm

**Comment by lamhoang1256** [comment]
@Khanhtran47 nếu bỏ refer, origin ra không truyền params gì hết thì vẫn bị **403** bác ạ. Mà nếu click vào link bị **403** đó thì nó mở tab mới rồi tải về file m3u8

![image](https://user-images.githubusercontent.com/61537853/223009120-3f43a649-0b59-48a1-a999-0d39d68e3992.png)

**Comment by lamhoang1256** [comment]
Em fix được rồi nhé. Cám ơn bác nhiều lắm. 
Với sẵn khi e dùng web sora-anime của bác khi nhấn Watch now thì bị lỗi **There was an error: Missing params**
Bác có thể kiểm tra lại nhé

![image](https://user-images.githubusercontent.com/61537853/224002638-1691de0d-048f-404c-932c-29b1665e9258.png)
![image](https://user-images.githubusercontent.com/61537853/224002661-30683ca2-441c-4b24-be21-e1e98a7fd448.png)
